config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'articles/test', to: 'articles#test'
  get 'articles/export_blogs', to: "articles#export_blogs"
  resources :articles do
    resources :comments
  end
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  
  get 'reset_password', to: 'passwords#edit'
  patch 'reset_password', to: 'passwords#update'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  

  delete 'sign_out', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	include Visible
	has_many :comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  	belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end
  class_methods do
    def public_count
      where(status: 'public').count
    end
  end
  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }

	def self.from_omniauth(auth)
		where(email: auth.info.email).first_or_initialize do |user|
		  user.name = auth.info.name
		  user.email = auth.info.email
		  user.password_digest = SecureRandom.hex
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user
	helper_method :get_current_user

  before_action :require_user_logged_in!
	  def set_current_user
     	@current_user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    
    def require_user_logged_in!
      	redirect_to sign_in_path, alert: 'You must be signed in' if @current_user.nil?
    end

    def get_current_user
    	@current_user
    end
end

app/controllers/articles_controller.rb
require 'export_blog'
class ArticlesController < ApplicationController
	def index
	    @articles = Article.all
	end

	def show
	  	@article = Article.find(params[:id])
	end

	def new
	    @article = Article.new
	end

	def create
	    @article = Article.new(article_params)
	    if @article.save
			flash[:info] = 'New Artical created successfully !'
	    	redirect_to root_path
	    else
	    	flash.now[:danger] = 'There is an error creating the article'
	      	render :new
	    end
	end

	def edit
    	@article = Article.find(params[:id])
  	end

  	def update
   		 @article = Article.find(params[:id])

    	if @article.update(article_params)
			flash[:info] = 'Artical Updated successfully !'
     		 redirect_to @article
    	else
			flash.now[:danger] = 'There is an error while updating  the article'
     		 render :edit
    	end
  	end
  	def destroy
    	@article = Article.find(params[:id])
   	 	@article.destroy
   	 	redirect_to root_path
 	end

	def test
		respond_to do |format|
			format.json {render :json => Article.all}
			format.xml {render :xml => Article.all}
		end
	end

	def export_blogs 
		export_blog = ExportBlog.new
		file_location = export_blog.export_blogs
		# in file_location path our excel file is ready, now we want to download it by using  
		# send_file method.
		send_file file_location,
				:disposition => 'attachment',
				:type => "application/csv",
				:x_sendfile => true
	end

	private
	    def article_params
	      params.require(:article).permit(:title, :body, :status)
	    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	skip_before_action :verify_authenticity_token
	def create
		comment_params
		commenter = params[:commenter]
		body = params[:body]
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(body: body, commenter: commenter)
		respond_to do |format|
			format.html { redirect_to article_path(@article) }
			format.js 
		end
		# unless @comment
		# 	flash[:danger] = "something wrong !"	
		# end
		
		
	end
	def destroy
	    @article = Article.find(params[:article_id])
	    @comment = @article.comments.find(params[:id])
	    @comment.destroy
		respond_to do |format|
			format.js {render :create}
		end
	end
	private
    def comment_params
      params.permit(:commenter, :body, :article_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
	
	def edit
	end
	def update
    if get_current_user.update(password_params)
      redirect_to root_path, notice: 'Password Updated'
    else
      render :edit
    end
  end

  private
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	skip_before_action :require_user_logged_in!, only: [:new, :create] 
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_param)
		if @user.save
			session[:user_id] = @user.id
			flash[:info] = "Your Account has been created!"
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def user_param
		params.require(:user).permit(:email, :password, :password_confirmation, :name)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_user_logged_in!, only: [:new, :create, :omniauth]
	def new

	end

	def create
		@user = User.find_by(email: params[:email])
		if @user.present? && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			flash[:info] = 'Login Successfully '
			redirect_to root_path
		else
			flash.now[:alert] = 'Invalid email or password'
        	render :new
		end

	end

	def destroy
      session[:user_id] = nil
	  flash[:info] = 'Logged Out'
      redirect_to sign_in_path
    end

	def omniauth
		@user = User.from_omniauth(auth)
		@user.save
		session[:user_id] = @user.id
		redirect_to root_path
	end
	  private
	  def auth
		request.env['omniauth.auth']
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class= "center">
  <%= form_with model: temp, class: 'row g-3' do |form| %>
    <div class="col-md-6">
      <%= form.label :title, class: 'form-label' %><br>
      <%= form.text_field :title, class: 'form-control' %>
      <% temp.errors.full_messages_for(:title).each do |message| %>
        <div class= "text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class = "col-12">
      <%= form.label :body, class: 'form-label' %><br>
      <%= form.text_area :body, class: 'form-control' %>
      <% temp.errors.full_messages_for(:body).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
    <div>
    <%= form.label :status, class: 'form-label' %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public', class: 'form-select' %>
    </div>

    
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/articles/_temp.html.erb
<p    class="form-container">
   <strong>Name:</strong>
   <%= @article.title %>
</p>

app/views/articles/check.js.erb
document.getElementById('current_customer').innerHTML = "<%=j render  partial: 'articles/temp', locals: { article: @article }  %>";

document.getElementById("current_customer").style.display = "block";

app/views/articles/edit.html.erb
<h1 class = "center-heading p-3" >Edit Article</h1>
<%= render "form", temp: @article %>

app/views/articles/index.html.erb
<div id="current_customer" class="form-popup" style="display:none;">

</div>
 <% if get_current_user %>
	<div class="row row-cols-1 row-cols-md-3 g-4 p-3">
	  <% @articles.each do |article| %>
		  <% unless article.archived? %>
		    <div class="col">
				<div class="card h-100">
				<div class="card-body">
					<h5 class="card-title"><%= article.title %></h5>
					<p class="card-text"><%= article.body[0,60] + " ..." %></p>
				</div>
				<div class="card-footer">
					<small class="text-muted">Last updated <%= article.updated_at.to_date.strftime('%d-%m-%Y') %></small>
					<%= link_to 'open', article_path(article), class: "right"%>
					<%= link_to 'popup', articles_check_path(article, id: article.id, format: :js), remote: true %>		
				</div>
				</div>
			</div>
		  <% end %>
	  <% end %>
	  </div>
  <br><br>  
  <% end %>

app/views/articles/new.html.erb
<h1 class = "center-heading">New Article</h1>

<%= render "form", temp: @article %>

app/views/articles/show.html.erb
<div class="center-70"> 
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<input type='hidden' id='article_id' name="article_id" value='<%= @article.id %>'  />
<div>
  <ul class = "list-group list-group-horizontal black">
  <li><%= link_to "Edit Article", edit_article_path(@article), class: 'list-group-item' %></li>
  <li><%= link_to "Destroy Article", article_path(@article), class: 'list-group-item',
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  </ul>
</div>
</div>

<div class="center-70">
<h4>Comments</h2>
<div id="comments_partial">
<%= render @article.comments %>
</div>
<p>
  <button class="btn-sm" id="comment_btn" >
   Add comments
  </button>
</p>
<div class="w-auto p-3">
  <div class="card card-body hide" id='add_comment'>
    <%= render 'comments/form' %>
  </div>
</div>



</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <% user = User.find(comment.commenter.to_i).name 
     user ||= "Unknown"   
  %>
  <%= user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment], remote: true, 
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/comments/_form.html.erb
<div class="w-auto p-3">
  <textarea name='body' class= "w-auto p-3" rows='3' id="comment_text"></textarea>
  <input type='submit' id='publish_comment' value='Publish'/>
  <input type='hidden' id='current_user_id' value='<%= get_current_user.id %>'  />
</div>

app/views/comments/create.js.erb
document.getElementById('comments_partial').innerHTML = "<%=j render @article.comments %>";

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
    <meta name="viewport" content="width=1024">
  </head>

  <body class="main_body">
  <% if get_current_user %>
  <ul class="nav justify-content-end pe-2 pt-2 pb-2 ">
    <li class="nav-item item-custom btn btn-primary">
    <div class="p-2 black">
      New Article
      <%= link_to "", new_article_path, class: 'plus radius' %> 
	  </div>
    </li>
    <li class="nav-item item-custom btn btn-primary">
      <div class = "btn">
       <%= link_to 'Export Blogs', articles_export_blogs_path, class: 'black' %>
      </div>
    </li>
    <li class="nav-item item-custom btn btn-primary">
      <div class = "btn ">
       <%= link_to 'HOME', root_path, class: 'black' %>
      </div>
    </li>
    <li class="nav-item item-custom btn btn-primary">
      <div class = "btn">
       <%= link_to 'Change Password ', reset_password_path(get_current_user), class: 'black' %>
      </div>
    </li>
    <li class="nav-item item-custom btn btn-primary">
      <div class = "btn">
       <%= link_to 'Logout ', sign_out_path, method: 'delete', class: 'black'  %>
      </div>
    </li>
  </ul>
  <% end %>
  <% flash.each do |name,message|%>
    <div class="alert alert-<%=name%> center-flash" role="alert">
        <%= message %>
    </div>
  <% end %>
  <%= yield %>
   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </body>
</html>